### PR TITLE
Optionally include cookies and requests in JSON

### PR DESCRIPTION
**Pull request by andersju**
I've found PhearJS to be immensely useful for a project I'm working on, but I also needed it to return all cookies (including ones set by JS) and all HTTP requests generated by a page. Not sure if it's out of scope for this project, but this makes it possible with two new parameters, **get_requests** and **get_cookies**, both _false_ by default.

Very simple change, with the disclaimer that I'm certainly no JS/CoffeeScript wiz (and I'm new to PhantomJS), but it's been working well for me.

### CODE REVIEW

**Comment by Tomtomgo** [comment]
@andersju thanks a lot! Seems like a useful addition. I will take a good look at it soon.

**Comment by Tomtomgo** [comment]
Merged this one, thanks a lot @andersju :+1: :100:

**Comment by thomasmodeneis** [comment]
Sorry mate, I implemented this in my fork and forgot to come back here.
I will test this implementation later on, thanks for this :)
Cheers

**Comment by andersju** [comment]
@Tomtomgo: Sweet! And thanks for your work!

**Pull request merged**
